kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: gitlab
  name: 'system:openshift:scc:anyuid-catalog'
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
