apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    name: gitlab-redis
  name: gitlab-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    name: gitlab-redis
